{ config, pkgs, ... }:

{
  home.packages = [ pkgs.matugen ];

  xdg.configFile."matugen/config.toml".text = ''
    [config]
    wallpaper_dir = "~/.config/matugen/"

    [templates.hyprland]
    input_path = "~/.config/matugen/templates/hyprland-colors.conf"
    output_path = "~/.config/hypr/colors.conf"
    [templates.hyprlock]
    input_path = "~/.config/matugen/templates/hyprlock-colors.conf"
    output_path = "~/.config/hypr/hyprlock-colors.conf"
    [templates.cava]
    input_path = "~/.config/matugen/templates/cava-colors.ini"
    output_path = "~/.config/cava/themes/colors"
    post_hook = "pkill -USR1 cava || true"
    [templates.kitty]
    input_path = "~/.config/matugen/templates/kitty-colors.conf"
    output_path = "~/.config/kitty/current-theme.conf"
    [templates.quickshell]
    input_path = "~/.config/matugen/templates/quickshell-colors.json"
    output_path = "~/.config/quickshell/colors.json"
  '';

  xdg.configFile."matugen/templates/cava-colors.ini".text = ''
    [color]
    foreground = '{{colors.primary.default.hex}}'

    gradient = 1
    gradient_color_1 = '{{colors.primary_container.default.hex}}'
    gradient_color_2 = '{{colors.primary.default.hex}}'
    gradient_color_3 = '{{colors.on_primary_container.default.hex}}'

    horizontal_gradient = 0
    horizontal_gradient_color_1 = '{{colors.primary_container.default.hex}}'
    horizontal_gradient_color_2 = '{{colors.primary.default.hex}}'
    horizontal_gradient_color_3 = '{{colors.on_primary_container.default.hex}}'
    horizontal_gradient_color_4 = '{{colors.primary.default.hex}}'
    horizontal_gradient_color_5 = '{{colors.primary_container.default.hex}}'
  '';

  xdg.configFile."matugen/templates/hyprland-colors.conf".text = ''
    # Generated by matugen — do not edit manually
    # Template: ~/.config/matugen/templates/hyprland-colors.conf
    # Output:   ~/.config/hypr/colors.conf

    $primary           = rgba({{colors.primary.default.hex_stripped}}ff)
    $secondary         = rgba({{colors.secondary.default.hex_stripped}}ff)
    $background        = rgba({{colors.background.default.hex_stripped}}ff)
    $on_background     = rgba({{colors.on_background.default.hex_stripped}}ff)
    $primary_container = rgba({{colors.primary_container.default.hex_stripped}}ff)
  '';

  xdg.configFile."matugen/templates/hyprlock-colors.conf".text = ''
    # ~/.config/matugen/templates/hyprlock-colors.conf
    $primary_container = rgb({{colors.primary_container.default.hex_stripped}})
    $on_primary_container = rgb({{colors.on_primary_container.default.hex_stripped}})
    $outline = rgb({{colors.outline.default.hex_stripped}})
    $backgroundAA = rgba({{colors.background.default.red}}, {{colors.background.default.green}}, {{colors.background.default.blue}}, 0.5)

    # This variable allows hyprlock to always find your current wallpaper
    $current_wallpaper = {{image}}
  '';

  xdg.configFile."matugen/templates/kitty-colors.conf".text = ''
    color0  {{colors.surface.default.hex}}
    color1  {{colors.error.default.hex}}
    color2  {{colors.primary.default.hex}}
    color3  {{colors.secondary.default.hex}}
    color4  {{colors.tertiary.default.hex}}
    color5  {{colors.primary.default.hex}}
    color6  {{colors.secondary.default.hex}}
    color7  {{colors.on_surface.default.hex}}
    color8  {{colors.outline.default.hex}}
    color9  {{colors.error.default.hex}}
    color10 {{colors.primary.default.hex}}
    color11 {{colors.secondary.default.hex}}
    color12 {{colors.tertiary.default.hex}}
    color13 {{colors.primary.default.hex}}
    color14 {{colors.secondary.default.hex}}
    color15 {{colors.on_surface.default.hex}}

    cursor                {{colors.on_surface.default.hex}}
    cursor_text_color     {{colors.surface.default.hex}}
    background            {{colors.surface.default.hex}}
    foreground            {{colors.on_surface.default.hex}}
    selection_foreground  {{colors.on_surface_variant.default.hex}}
    selection_background  {{colors.surface_variant.default.hex}}
    active_border_color   {{colors.primary.default.hex}}
    inactive_border_color {{colors.surface_variant.default.hex}}
    url_color             {{colors.primary.default.hex}}
  '';

  xdg.configFile."matugen/templates/notif-colors.conf".text = ''
    # Matugen-generated dunst colors
    # Generated by matugen — do not edit directly
    # Input: ~/.config/matugen/templates/dunst-colors.conf
    # Output: ~/.config/dunst/dunstrc

    [global]
        ### Display ###
        monitor = 1
        follow = none

        ### Geometry ###
        width = 370
        height = (0, 200)
        origin = top-right
        offset = (20, 10)
        scale = 0
        notification_limit = 5

        ### Appearance ###
        transparency = 0
        separator_height = 2
        padding = 15
        horizontal_padding = 15
        text_icon_padding = 15
        frame_width = 2
        frame_color = "#{{colors.primary.default.hex_stripped}}cc"
        gap_size = 10
        separator_color = frame
        sort = yes
        corner_radius = 14
        corners = all

        ### Icons ###
        icon_theme = "hicolor"
        enable_recursive_icon_lookup = true
        icon_position = left
        min_icon_size = 48
        max_icon_size = 48

        ### Text ###
        font = Sans 12
        line_height = 0
        markup = full
        format = "<b>%s</b>\n%b"
        alignment = left
        vertical_alignment = center
        show_age_threshold = 60
        ellipsize = middle
        ignore_newline = no
        stack_duplicates = true
        hide_duplicate_count = false
        show_indicators = yes
        word_wrap = yes

        ### Mouse ###
        mouse_left_click = do_action, close_current
        mouse_middle_click = close_all
        mouse_right_click = close_current

        ### Misc ###
        dmenu = /usr/bin/dmenu -p dunst:
        browser = /usr/bin/xdg-open
        always_run_script = true
        title = Dunst
        class = Dunst
        ignore_dbusclose = false
        force_xwayland = false
        force_xinerama = false
        sticky_history = yes
        history_length = 20
        script = /home/stellanova/.config/eww/scripts/dunst_logger.sh

    [urgency_low]
        background = "{{colors.background.default.hex}}a6"
        foreground = "#{{colors.on_surface.default.hex_stripped}}"
        frame_color = "#{{colors.primary.default.hex_stripped}}cc"
        timeout = 5
        default_icon = dialog-information

    [urgency_normal]
        background = "{{colors.background.default.hex}}a6"
        foreground = "#{{colors.on_surface.default.hex_stripped}}"
        frame_color = "#{{colors.primary.default.hex_stripped}}cc"
        timeout = 5

    [urgency_critical]
        background = "{{colors.background.default.hex}}a6"
        foreground = "#{{colors.on_surface.default.hex_stripped}}"
        frame_color = "#{{colors.primary.default.hex_stripped}}cc"
        timeout = 0
  '';

  xdg.configFile."matugen/templates/quickshell-colors.json".text = ''
    {
      "primary": "{{colors.primary.default.hex}}",
      "primaryContainer": "{{colors.primary_container.default.hex}}",
      "secondary": "{{colors.secondary.default.hex}}",
      "background": "{{colors.background.default.hex}}",
      "surface": "{{colors.surface.default.hex}}",
      "onSurface": "{{colors.on_surface.default.hex}}",
      "onPrimary": "{{colors.on_primary.default.hex}}"
    }
  '';
}
