{ lib, ... }:
let
  toZsh =
    name: value:
    if builtins.isList value then
      "typeset -g ${name}=(${
        lib.concatStringsSep " " (map (v: if builtins.isString v then v else builtins.toString v) value)
      })"
    else if builtins.isBool value then
      "typeset -g ${name}=${if value then "true" else "false"}"
    else if builtins.isString value && (lib.hasPrefix "''" value || lib.hasPrefix "'" value) then
      "typeset -g ${name}=${value}"
    else if builtins.isInt value then
      "typeset -g ${name}=${builtins.toString value}"
    else
      "typeset -g ${name}='${builtins.toString value}'";

  settings = {
    POWERLEVEL9K_MODE = "nerdfont-v3";
    POWERLEVEL9K_ICON_PADDING = "none";
    POWERLEVEL9K_ICON_BEFORE_CONTENT = "";
    POWERLEVEL9K_PROMPT_ADD_NEWLINE = true;

    POWERLEVEL9K_LEFT_PROMPT_ELEMENTS = [
      "os_icon"
      "dir"
      "vcs"
      "newline"
    ];

    POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS = [
      "status"
      "command_execution_time"
      "background_jobs"
      "direnv"
      "asdf"
      "virtualenv"
      "anaconda"
      "pyenv"
      "goenv"
      "nodenv"
      "nvm"
      "nodeenv"
      "rbenv"
      "rvm"
      "fvm"
      "luaenv"
      "jenv"
      "plenv"
      "perlbrew"
      "phpenv"
      "scalaenv"
      "haskell_stack"
      "kubecontext"
      "terraform"
      "aws"
      "aws_eb_env"
      "azure"
      "gcloud"
      "google_app_cred"
      "toolbox"
      "context"
      "nordvpn"
      "ranger"
      "yazi"
      "nnn"
      "lf"
      "xplr"
      "vim_shell"
      "midnight_commander"
      "nix_shell"
      "chezmoi_shell"
      "vi_mode"
      "todo"
      "timewarrior"
      "taskwarrior"
      "per_directory_history"
      "newline"
    ];

    # Multiline ornaments
    POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX = "%244F╭─";
    POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX = "%244F├─";
    POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX = "%244F╰─";
    POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX = "";
    POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX = "";
    POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX = "";
    POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR = " ";
    POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_BACKGROUND = "";
    POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_GAP_BACKGROUND = "";

    # Separators (slanted/round per wizard options)
    POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR = "\\u2571";
    POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR = "\\u2571";
    POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR = "\\uE0BC";
    POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR = "\\uE0BA";
    POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL = "\\uE0B4";
    POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL = "\\uE0B6";
    POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL = "\\uE0B6";
    POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL = "\\uE0B4";
    POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL = "";

    # OS Icon
    POWERLEVEL9K_OS_ICON_FOREGROUND = 232;
    POWERLEVEL9K_OS_ICON_BACKGROUND = 7;

    # Prompt char (not in prompt elements but settings kept for completeness)
    POWERLEVEL9K_PROMPT_CHAR_BACKGROUND = "";
    POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND = 76;
    POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND = 76;
    POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_FOREGROUND = 76;
    POWERLEVEL9K_PROMPT_CHAR_OK_VIOWR_FOREGROUND = 76;
    POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND = 196;
    POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_FOREGROUND = 196;
    POWERLEVEL9K_PROMPT_CHAR_ERROR_VIVIS_FOREGROUND = 196;
    POWERLEVEL9K_PROMPT_CHAR_ERROR_VIOWR_FOREGROUND = 196;
    POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION = "❯";
    POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_CONTENT_EXPANSION = "❯";
    POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_CONTENT_EXPANSION = "❮";
    POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_CONTENT_EXPANSION = "❮";
    POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_CONTENT_EXPANSION = "V";
    POWERLEVEL9K_PROMPT_CHAR_ERROR_VIVIS_CONTENT_EXPANSION = "V";
    POWERLEVEL9K_PROMPT_CHAR_OK_VIOWR_CONTENT_EXPANSION = "▶";
    POWERLEVEL9K_PROMPT_CHAR_ERROR_VIOWR_CONTENT_EXPANSION = "▶";
    POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE = true;
    POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL = "";
    POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL = "";
    POWERLEVEL9K_PROMPT_CHAR_LEFT_LEFT_WHITESPACE = "";
    POWERLEVEL9K_PROMPT_CHAR_LEFT_RIGHT_WHITESPACE = "";

    # Directory
    POWERLEVEL9K_DIR_BACKGROUND = 4;
    POWERLEVEL9K_DIR_FOREGROUND = 254;
    POWERLEVEL9K_SHORTEN_STRATEGY = "truncate_to_unique";
    POWERLEVEL9K_SHORTEN_DELIMITER = "";
    POWERLEVEL9K_DIR_SHORTENED_FOREGROUND = 250;
    POWERLEVEL9K_DIR_ANCHOR_FOREGROUND = 255;
    POWERLEVEL9K_DIR_ANCHOR_BOLD = true;
    POWERLEVEL9K_SHORTEN_FOLDER_MARKER = "(.bzr|.citc|.git|.hg|.node-version|.python-version|.go-version|.ruby-version|.lua-version|.java-version|.perl-version|.php-version|.tool-versions|.mise.toml|.shorten_folder_marker|.svn|.terraform|CVS|Cargo.toml|composer.json|go.mod|package.json|stack.yaml)";
    POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER = false;
    POWERLEVEL9K_SHORTEN_DIR_LENGTH = 1;
    POWERLEVEL9K_DIR_MAX_LENGTH = 80;
    POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS = 40;
    POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT = 50;
    POWERLEVEL9K_DIR_HYPERLINK = false;
    POWERLEVEL9K_DIR_SHOW_WRITABLE = "v3";

    # VCS (Git)
    POWERLEVEL9K_VCS_CLEAN_BACKGROUND = 2;
    POWERLEVEL9K_VCS_MODIFIED_BACKGROUND = 3;
    POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND = 2;
    POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND = 3;
    POWERLEVEL9K_VCS_LOADING_BACKGROUND = 8;
    POWERLEVEL9K_VCS_BRANCH_ICON = "\\uF126 ";
    POWERLEVEL9K_VCS_UNTRACKED_ICON = "?";
    POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY = -1;
    POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN = "~";
    POWERLEVEL9K_VCS_BACKENDS = [ "git" ];
    POWERLEVEL9K_VCS_STAGED_MAX_NUM = -1;
    POWERLEVEL9K_VCS_UNSTAGED_MAX_NUM = -1;
    POWERLEVEL9K_VCS_UNTRACKED_MAX_NUM = -1;
    POWERLEVEL9K_VCS_CONFLICTED_MAX_NUM = -1;
    POWERLEVEL9K_VCS_COMMITS_AHEAD_MAX_NUM = -1;
    POWERLEVEL9K_VCS_COMMITS_BEHIND_MAX_NUM = -1;

    # Status
    POWERLEVEL9K_STATUS_EXTENDED_STATES = true;
    POWERLEVEL9K_STATUS_OK = true;
    POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION = "✔";
    POWERLEVEL9K_STATUS_OK_FOREGROUND = 2;
    POWERLEVEL9K_STATUS_OK_BACKGROUND = 0;
    POWERLEVEL9K_STATUS_OK_PIPE = true;
    POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION = "✔";
    POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND = 2;
    POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND = 0;
    POWERLEVEL9K_STATUS_ERROR = true;
    POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION = "✘";
    POWERLEVEL9K_STATUS_ERROR_FOREGROUND = 3;
    POWERLEVEL9K_STATUS_ERROR_BACKGROUND = 1;
    POWERLEVEL9K_STATUS_ERROR_SIGNAL = true;
    POWERLEVEL9K_STATUS_VERBOSE_SIGNAME = false;
    POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION = "✘";
    POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND = 3;
    POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND = 1;
    POWERLEVEL9K_STATUS_ERROR_PIPE = true;
    POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION = "✘";
    POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND = 3;
    POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND = 1;

    # Command execution time
    POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND = 0;
    POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND = 3;
    POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD = 3;
    POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION = 0;
    POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT = "d h m s";

    # Background jobs
    POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND = 6;
    POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND = 0;
    POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE = false;

    # Direnv
    POWERLEVEL9K_DIRENV_FOREGROUND = 3;
    POWERLEVEL9K_DIRENV_BACKGROUND = 0;

    # Asdf
    POWERLEVEL9K_ASDF_FOREGROUND = 0;
    POWERLEVEL9K_ASDF_BACKGROUND = 7;
    POWERLEVEL9K_ASDF_SOURCES = [
      "shell"
      "local"
      "global"
    ];
    POWERLEVEL9K_ASDF_PROMPT_ALWAYS_SHOW = false;
    POWERLEVEL9K_ASDF_SHOW_SYSTEM = true;
    POWERLEVEL9K_ASDF_SHOW_ON_UPGLOB = "";
    POWERLEVEL9K_ASDF_RUBY_FOREGROUND = 0;
    POWERLEVEL9K_ASDF_RUBY_BACKGROUND = 1;
    POWERLEVEL9K_ASDF_PYTHON_FOREGROUND = 0;
    POWERLEVEL9K_ASDF_PYTHON_BACKGROUND = 4;
    POWERLEVEL9K_ASDF_GOLANG_FOREGROUND = 0;
    POWERLEVEL9K_ASDF_GOLANG_BACKGROUND = 4;
    POWERLEVEL9K_ASDF_NODEJS_FOREGROUND = 0;
    POWERLEVEL9K_ASDF_NODEJS_BACKGROUND = 2;
    POWERLEVEL9K_ASDF_RUST_FOREGROUND = 0;
    POWERLEVEL9K_ASDF_RUST_BACKGROUND = 208;
    POWERLEVEL9K_ASDF_DOTNET_CORE_FOREGROUND = 0;
    POWERLEVEL9K_ASDF_DOTNET_CORE_BACKGROUND = 5;
    POWERLEVEL9K_ASDF_FLUTTER_FOREGROUND = 0;
    POWERLEVEL9K_ASDF_FLUTTER_BACKGROUND = 4;
    POWERLEVEL9K_ASDF_LUA_FOREGROUND = 0;
    POWERLEVEL9K_ASDF_LUA_BACKGROUND = 4;
    POWERLEVEL9K_ASDF_JAVA_FOREGROUND = 1;
    POWERLEVEL9K_ASDF_JAVA_BACKGROUND = 7;
    POWERLEVEL9K_ASDF_PERL_FOREGROUND = 0;
    POWERLEVEL9K_ASDF_PERL_BACKGROUND = 4;
    POWERLEVEL9K_ASDF_ERLANG_FOREGROUND = 0;
    POWERLEVEL9K_ASDF_ERLANG_BACKGROUND = 1;
    POWERLEVEL9K_ASDF_ELIXIR_FOREGROUND = 0;
    POWERLEVEL9K_ASDF_ELIXIR_BACKGROUND = 5;
    POWERLEVEL9K_ASDF_POSTGRES_FOREGROUND = 0;
    POWERLEVEL9K_ASDF_POSTGRES_BACKGROUND = 6;
    POWERLEVEL9K_ASDF_PHP_FOREGROUND = 0;
    POWERLEVEL9K_ASDF_PHP_BACKGROUND = 5;
    POWERLEVEL9K_ASDF_HASKELL_FOREGROUND = 0;
    POWERLEVEL9K_ASDF_HASKELL_BACKGROUND = 3;
    POWERLEVEL9K_ASDF_JULIA_FOREGROUND = 0;
    POWERLEVEL9K_ASDF_JULIA_BACKGROUND = 2;

    # NordVPN
    POWERLEVEL9K_NORDVPN_FOREGROUND = 7;
    POWERLEVEL9K_NORDVPN_BACKGROUND = 4;
    POWERLEVEL9K_NORDVPN_DISCONNECTED_CONTENT_EXPANSION = "";
    POWERLEVEL9K_NORDVPN_DISCONNECTED_VISUAL_IDENTIFIER_EXPANSION = "";
    POWERLEVEL9K_NORDVPN_CONNECTING_CONTENT_EXPANSION = "";
    POWERLEVEL9K_NORDVPN_CONNECTING_VISUAL_IDENTIFIER_EXPANSION = "";
    POWERLEVEL9K_NORDVPN_DISCONNECTING_CONTENT_EXPANSION = "";
    POWERLEVEL9K_NORDVPN_DISCONNECTING_VISUAL_IDENTIFIER_EXPANSION = "";

    # Shell type indicators
    POWERLEVEL9K_RANGER_FOREGROUND = 3;
    POWERLEVEL9K_RANGER_BACKGROUND = 0;
    POWERLEVEL9K_YAZI_FOREGROUND = 3;
    POWERLEVEL9K_YAZI_BACKGROUND = 0;
    POWERLEVEL9K_NNN_FOREGROUND = 0;
    POWERLEVEL9K_NNN_BACKGROUND = 6;
    POWERLEVEL9K_LF_FOREGROUND = 0;
    POWERLEVEL9K_LF_BACKGROUND = 6;
    POWERLEVEL9K_XPLR_FOREGROUND = 0;
    POWERLEVEL9K_XPLR_BACKGROUND = 6;
    POWERLEVEL9K_VIM_SHELL_FOREGROUND = 0;
    POWERLEVEL9K_VIM_SHELL_BACKGROUND = 2;
    POWERLEVEL9K_MIDNIGHT_COMMANDER_FOREGROUND = 3;
    POWERLEVEL9K_MIDNIGHT_COMMANDER_BACKGROUND = 0;

    # Nix shell
    POWERLEVEL9K_NIX_SHELL_FOREGROUND = 0;
    POWERLEVEL9K_NIX_SHELL_BACKGROUND = 4;

    # Chezmoi shell
    POWERLEVEL9K_CHEZMOI_SHELL_FOREGROUND = 0;
    POWERLEVEL9K_CHEZMOI_SHELL_BACKGROUND = 4;

    # Disk usage
    POWERLEVEL9K_DISK_USAGE_NORMAL_FOREGROUND = 3;
    POWERLEVEL9K_DISK_USAGE_NORMAL_BACKGROUND = 0;
    POWERLEVEL9K_DISK_USAGE_WARNING_FOREGROUND = 0;
    POWERLEVEL9K_DISK_USAGE_WARNING_BACKGROUND = 3;
    POWERLEVEL9K_DISK_USAGE_CRITICAL_FOREGROUND = 7;
    POWERLEVEL9K_DISK_USAGE_CRITICAL_BACKGROUND = 1;
    POWERLEVEL9K_DISK_USAGE_WARNING_LEVEL = 90;
    POWERLEVEL9K_DISK_USAGE_CRITICAL_LEVEL = 95;
    POWERLEVEL9K_DISK_USAGE_ONLY_WARNING = false;

    # Vi mode
    POWERLEVEL9K_VI_MODE_FOREGROUND = 0;
    POWERLEVEL9K_VI_COMMAND_MODE_STRING = "NORMAL";
    POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND = 2;
    POWERLEVEL9K_VI_VISUAL_MODE_STRING = "VISUAL";
    POWERLEVEL9K_VI_MODE_VISUAL_BACKGROUND = 4;
    POWERLEVEL9K_VI_OVERWRITE_MODE_STRING = "OVERTYPE";
    POWERLEVEL9K_VI_MODE_OVERWRITE_BACKGROUND = 3;
    POWERLEVEL9K_VI_INSERT_MODE_STRING = "";
    POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND = 8;

    # RAM / Swap / Load
    POWERLEVEL9K_RAM_FOREGROUND = 0;
    POWERLEVEL9K_RAM_BACKGROUND = 3;
    POWERLEVEL9K_SWAP_FOREGROUND = 0;
    POWERLEVEL9K_SWAP_BACKGROUND = 3;
    POWERLEVEL9K_LOAD_WHICH = 5;
    POWERLEVEL9K_LOAD_NORMAL_FOREGROUND = 0;
    POWERLEVEL9K_LOAD_NORMAL_BACKGROUND = 2;
    POWERLEVEL9K_LOAD_WARNING_FOREGROUND = 0;
    POWERLEVEL9K_LOAD_WARNING_BACKGROUND = 3;
    POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND = 0;
    POWERLEVEL9K_LOAD_CRITICAL_BACKGROUND = 1;

    # Todo
    POWERLEVEL9K_TODO_FOREGROUND = 0;
    POWERLEVEL9K_TODO_BACKGROUND = 8;
    POWERLEVEL9K_TODO_HIDE_ZERO_TOTAL = true;
    POWERLEVEL9K_TODO_HIDE_ZERO_FILTERED = false;

    # Timewarrior
    POWERLEVEL9K_TIMEWARRIOR_FOREGROUND = 255;
    POWERLEVEL9K_TIMEWARRIOR_BACKGROUND = 8;
    POWERLEVEL9K_TIMEWARRIOR_CONTENT_EXPANSION = "'\${P9K_CONTENT:0:24}\${\${P9K_CONTENT:24}:+…}'";

    # Taskwarrior
    POWERLEVEL9K_TASKWARRIOR_FOREGROUND = 0;
    POWERLEVEL9K_TASKWARRIOR_BACKGROUND = 6;

    # Per-directory history
    POWERLEVEL9K_PER_DIRECTORY_HISTORY_LOCAL_FOREGROUND = 0;
    POWERLEVEL9K_PER_DIRECTORY_HISTORY_LOCAL_BACKGROUND = 5;
    POWERLEVEL9K_PER_DIRECTORY_HISTORY_GLOBAL_FOREGROUND = 0;
    POWERLEVEL9K_PER_DIRECTORY_HISTORY_GLOBAL_BACKGROUND = 3;

    # CPU arch
    POWERLEVEL9K_CPU_ARCH_FOREGROUND = 0;
    POWERLEVEL9K_CPU_ARCH_BACKGROUND = 3;

    # Context
    POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND = 1;
    POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND = 0;
    POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND = 3;
    POWERLEVEL9K_CONTEXT_REMOTE_SUDO_FOREGROUND = 3;
    POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND = 0;
    POWERLEVEL9K_CONTEXT_REMOTE_SUDO_BACKGROUND = 0;
    POWERLEVEL9K_CONTEXT_FOREGROUND = 3;
    POWERLEVEL9K_CONTEXT_BACKGROUND = 0;
    POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE = "%n@%m";
    POWERLEVEL9K_CONTEXT_REMOTE_TEMPLATE = "%n@%m";
    POWERLEVEL9K_CONTEXT_REMOTE_SUDO_TEMPLATE = "%n@%m";
    POWERLEVEL9K_CONTEXT_TEMPLATE = "%n@%m";
    POWERLEVEL9K_CONTEXT_DEFAULT_CONTENT_EXPANSION = "";
    POWERLEVEL9K_CONTEXT_DEFAULT_VISUAL_IDENTIFIER_EXPANSION = "";
    POWERLEVEL9K_CONTEXT_SUDO_CONTENT_EXPANSION = "";
    POWERLEVEL9K_CONTEXT_SUDO_VISUAL_IDENTIFIER_EXPANSION = "";

    # Virtualenv
    POWERLEVEL9K_VIRTUALENV_FOREGROUND = 0;
    POWERLEVEL9K_VIRTUALENV_BACKGROUND = 4;
    POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION = false;
    POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV = false;
    POWERLEVEL9K_VIRTUALENV_LEFT_DELIMITER = "";
    POWERLEVEL9K_VIRTUALENV_RIGHT_DELIMITER = "";

    # Anaconda
    POWERLEVEL9K_ANACONDA_FOREGROUND = 0;
    POWERLEVEL9K_ANACONDA_BACKGROUND = 4;
    POWERLEVEL9K_ANACONDA_CONTENT_EXPANSION = "'\${\${\${\${CONDA_PROMPT_MODIFIER#\\(}% }%\\)}:-\${CONDA_PREFIX:t}}'";

    # Pyenv
    POWERLEVEL9K_PYENV_FOREGROUND = 0;
    POWERLEVEL9K_PYENV_BACKGROUND = 4;
    POWERLEVEL9K_PYENV_SOURCES = [
      "shell"
      "local"
      "global"
    ];
    POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW = false;
    POWERLEVEL9K_PYENV_SHOW_SYSTEM = true;
    POWERLEVEL9K_PYENV_CONTENT_EXPANSION = "'\${P9K_CONTENT}\${\${P9K_CONTENT:#$P9K_PYENV_PYTHON_VERSION(|/*)}:+ $P9K_PYENV_PYTHON_VERSION}'";

    # Goenv
    POWERLEVEL9K_GOENV_FOREGROUND = 0;
    POWERLEVEL9K_GOENV_BACKGROUND = 4;
    POWERLEVEL9K_GOENV_SOURCES = [
      "shell"
      "local"
      "global"
    ];
    POWERLEVEL9K_GOENV_PROMPT_ALWAYS_SHOW = false;
    POWERLEVEL9K_GOENV_SHOW_SYSTEM = true;

    # Nodenv
    POWERLEVEL9K_NODENV_FOREGROUND = 2;
    POWERLEVEL9K_NODENV_BACKGROUND = 0;
    POWERLEVEL9K_NODENV_SOURCES = [
      "shell"
      "local"
      "global"
    ];
    POWERLEVEL9K_NODENV_PROMPT_ALWAYS_SHOW = false;
    POWERLEVEL9K_NODENV_SHOW_SYSTEM = true;

    # Nvm
    POWERLEVEL9K_NVM_FOREGROUND = 0;
    POWERLEVEL9K_NVM_BACKGROUND = 5;
    POWERLEVEL9K_NVM_PROMPT_ALWAYS_SHOW = false;
    POWERLEVEL9K_NVM_SHOW_SYSTEM = true;

    # Nodeenv
    POWERLEVEL9K_NODEENV_FOREGROUND = 2;
    POWERLEVEL9K_NODEENV_BACKGROUND = 0;
    POWERLEVEL9K_NODEENV_SHOW_NODE_VERSION = false;
    POWERLEVEL9K_NODEENV_LEFT_DELIMITER = "";
    POWERLEVEL9K_NODEENV_RIGHT_DELIMITER = "";

    # Node version
    POWERLEVEL9K_NODE_VERSION_FOREGROUND = 7;
    POWERLEVEL9K_NODE_VERSION_BACKGROUND = 2;
    POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY = true;

    # Go version
    POWERLEVEL9K_GO_VERSION_FOREGROUND = 255;
    POWERLEVEL9K_GO_VERSION_BACKGROUND = 2;
    POWERLEVEL9K_GO_VERSION_PROJECT_ONLY = true;

    # Rust version
    POWERLEVEL9K_RUST_VERSION_FOREGROUND = 0;
    POWERLEVEL9K_RUST_VERSION_BACKGROUND = 208;
    POWERLEVEL9K_RUST_VERSION_PROJECT_ONLY = true;

    # Dotnet version
    POWERLEVEL9K_DOTNET_VERSION_FOREGROUND = 7;
    POWERLEVEL9K_DOTNET_VERSION_BACKGROUND = 5;
    POWERLEVEL9K_DOTNET_VERSION_PROJECT_ONLY = true;

    # PHP version
    POWERLEVEL9K_PHP_VERSION_FOREGROUND = 0;
    POWERLEVEL9K_PHP_VERSION_BACKGROUND = 5;
    POWERLEVEL9K_PHP_VERSION_PROJECT_ONLY = true;

    # Laravel version
    POWERLEVEL9K_LARAVEL_VERSION_FOREGROUND = 1;
    POWERLEVEL9K_LARAVEL_VERSION_BACKGROUND = 7;

    # Rbenv
    POWERLEVEL9K_RBENV_FOREGROUND = 0;
    POWERLEVEL9K_RBENV_BACKGROUND = 1;
    POWERLEVEL9K_RBENV_SOURCES = [
      "shell"
      "local"
      "global"
    ];
    POWERLEVEL9K_RBENV_PROMPT_ALWAYS_SHOW = false;
    POWERLEVEL9K_RBENV_SHOW_SYSTEM = true;

    # Java version
    POWERLEVEL9K_JAVA_VERSION_FOREGROUND = 1;
    POWERLEVEL9K_JAVA_VERSION_BACKGROUND = 7;
    POWERLEVEL9K_JAVA_VERSION_PROJECT_ONLY = true;
    POWERLEVEL9K_JAVA_VERSION_FULL = false;

    # Package
    POWERLEVEL9K_PACKAGE_FOREGROUND = 0;
    POWERLEVEL9K_PACKAGE_BACKGROUND = 6;

    # Rvm
    POWERLEVEL9K_RVM_FOREGROUND = 0;
    POWERLEVEL9K_RVM_BACKGROUND = 240;
    POWERLEVEL9K_RVM_SHOW_GEMSET = false;
    POWERLEVEL9K_RVM_SHOW_PREFIX = false;

    # Fvm
    POWERLEVEL9K_FVM_FOREGROUND = 0;
    POWERLEVEL9K_FVM_BACKGROUND = 4;

    # Luaenv
    POWERLEVEL9K_LUAENV_FOREGROUND = 0;
    POWERLEVEL9K_LUAENV_BACKGROUND = 4;
    POWERLEVEL9K_LUAENV_SOURCES = [
      "shell"
      "local"
      "global"
    ];
    POWERLEVEL9K_LUAENV_PROMPT_ALWAYS_SHOW = false;
    POWERLEVEL9K_LUAENV_SHOW_SYSTEM = true;

    # Jenv
    POWERLEVEL9K_JENV_FOREGROUND = 1;
    POWERLEVEL9K_JENV_BACKGROUND = 7;
    POWERLEVEL9K_JENV_SOURCES = [
      "shell"
      "local"
      "global"
    ];
    POWERLEVEL9K_JENV_PROMPT_ALWAYS_SHOW = false;
    POWERLEVEL9K_JENV_SHOW_SYSTEM = true;

    # Plenv
    POWERLEVEL9K_PLENV_FOREGROUND = 0;
    POWERLEVEL9K_PLENV_BACKGROUND = 4;
    POWERLEVEL9K_PLENV_SOURCES = [
      "shell"
      "local"
      "global"
    ];
    POWERLEVEL9K_PLENV_PROMPT_ALWAYS_SHOW = false;
    POWERLEVEL9K_PLENV_SHOW_SYSTEM = true;

    # Perlbrew
    POWERLEVEL9K_PERLBREW_FOREGROUND = 67;
    POWERLEVEL9K_PERLBREW_PROJECT_ONLY = true;
    POWERLEVEL9K_PERLBREW_SHOW_PREFIX = false;

    # Phpenv
    POWERLEVEL9K_PHPENV_FOREGROUND = 0;
    POWERLEVEL9K_PHPENV_BACKGROUND = 5;
    POWERLEVEL9K_PHPENV_SOURCES = [
      "shell"
      "local"
      "global"
    ];
    POWERLEVEL9K_PHPENV_PROMPT_ALWAYS_SHOW = false;
    POWERLEVEL9K_PHPENV_SHOW_SYSTEM = true;

    # Scalaenv
    POWERLEVEL9K_SCALAENV_FOREGROUND = 0;
    POWERLEVEL9K_SCALAENV_BACKGROUND = 1;
    POWERLEVEL9K_SCALAENV_SOURCES = [
      "shell"
      "local"
      "global"
    ];
    POWERLEVEL9K_SCALAENV_PROMPT_ALWAYS_SHOW = false;
    POWERLEVEL9K_SCALAENV_SHOW_SYSTEM = true;

    # Haskell stack
    POWERLEVEL9K_HASKELL_STACK_FOREGROUND = 0;
    POWERLEVEL9K_HASKELL_STACK_BACKGROUND = 3;
    POWERLEVEL9K_HASKELL_STACK_SOURCES = [
      "shell"
      "local"
    ];
    POWERLEVEL9K_HASKELL_STACK_ALWAYS_SHOW = true;

    # Terraform
    POWERLEVEL9K_TERRAFORM_SHOW_DEFAULT = false;
    POWERLEVEL9K_TERRAFORM_CLASSES = [
      "'*'"
      "OTHER"
    ];
    POWERLEVEL9K_TERRAFORM_OTHER_FOREGROUND = 4;
    POWERLEVEL9K_TERRAFORM_OTHER_BACKGROUND = 0;
    POWERLEVEL9K_TERRAFORM_VERSION_FOREGROUND = 4;
    POWERLEVEL9K_TERRAFORM_VERSION_BACKGROUND = 0;

    # Kubecontext
    POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND = "kubectl|helm|kubens|kubectx|oc|istioctl|kogito|k9s|helmfile|flux|fluxctl|stern|kubeseal|skaffold|kubent|kubecolor|cmctl|sparkctl";
    POWERLEVEL9K_KUBECONTEXT_CLASSES = [
      "'*'"
      "DEFAULT"
    ];
    POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND = 7;
    POWERLEVEL9K_KUBECONTEXT_DEFAULT_BACKGROUND = 5;
    # Combined from the two += assignments in the original
    POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION = "'\${P9K_KUBECONTEXT_CLOUD_CLUSTER:-\${P9K_KUBECONTEXT_NAME}}\${\${:-/$P9K_KUBECONTEXT_NAMESPACE}:#/default}'";

    # AWS
    POWERLEVEL9K_AWS_SHOW_ON_COMMAND = "aws|awless|cdk|terraform|tofu|pulumi|terragrunt";
    POWERLEVEL9K_AWS_CLASSES = [
      "'*'"
      "DEFAULT"
    ];
    POWERLEVEL9K_AWS_DEFAULT_FOREGROUND = 7;
    POWERLEVEL9K_AWS_DEFAULT_BACKGROUND = 1;
    POWERLEVEL9K_AWS_CONTENT_EXPANSION = "'\${P9K_AWS_PROFILE//\\%/%%}\${P9K_AWS_REGION:+ \${P9K_AWS_REGION//\\%/%%}}'";

    # AWS Elastic Beanstalk
    POWERLEVEL9K_AWS_EB_ENV_FOREGROUND = 2;
    POWERLEVEL9K_AWS_EB_ENV_BACKGROUND = 0;

    # Azure
    POWERLEVEL9K_AZURE_SHOW_ON_COMMAND = "az|terraform|tofu|pulumi|terragrunt";
    POWERLEVEL9K_AZURE_CLASSES = [
      "'*'"
      "OTHER"
    ];
    POWERLEVEL9K_AZURE_OTHER_FOREGROUND = 7;
    POWERLEVEL9K_AZURE_OTHER_BACKGROUND = 4;

    # Gcloud
    POWERLEVEL9K_GCLOUD_SHOW_ON_COMMAND = "gcloud|gcs|gsutil";
    POWERLEVEL9K_GCLOUD_FOREGROUND = 7;
    POWERLEVEL9K_GCLOUD_BACKGROUND = 4;
    POWERLEVEL9K_GCLOUD_PARTIAL_CONTENT_EXPANSION = "'\${P9K_GCLOUD_PROJECT_ID//\\%/%%}'";
    POWERLEVEL9K_GCLOUD_COMPLETE_CONTENT_EXPANSION = "'\${P9K_GCLOUD_PROJECT_NAME//\\%/%%}'";
    POWERLEVEL9K_GCLOUD_REFRESH_PROJECT_NAME_SECONDS = 60;

    # Google App Cred
    POWERLEVEL9K_GOOGLE_APP_CRED_SHOW_ON_COMMAND = "terraform|tofu|pulumi|terragrunt";
    POWERLEVEL9K_GOOGLE_APP_CRED_CLASSES = [
      "'*'"
      "DEFAULT"
    ];
    POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_FOREGROUND = 7;
    POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_BACKGROUND = 4;
    POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_CONTENT_EXPANSION = "'\${P9K_GOOGLE_APP_CRED_PROJECT_ID//\\%/%%}'";

    # Toolbox
    POWERLEVEL9K_TOOLBOX_FOREGROUND = 0;
    POWERLEVEL9K_TOOLBOX_BACKGROUND = 3;
    POWERLEVEL9K_TOOLBOX_CONTENT_EXPANSION = "'\${P9K_TOOLBOX_NAME:#fedora-toolbox-*}'";

    # Public IP
    POWERLEVEL9K_PUBLIC_IP_FOREGROUND = 7;
    POWERLEVEL9K_PUBLIC_IP_BACKGROUND = 0;

    # VPN IP
    POWERLEVEL9K_VPN_IP_FOREGROUND = 0;
    POWERLEVEL9K_VPN_IP_BACKGROUND = 6;
    POWERLEVEL9K_VPN_IP_CONTENT_EXPANSION = "";
    POWERLEVEL9K_VPN_IP_INTERFACE = "'(gpd|wg|(.*tun)|tailscale)[0-9]*|(zt.*)'";
    POWERLEVEL9K_VPN_IP_SHOW_ALL = false;

    # IP
    POWERLEVEL9K_IP_BACKGROUND = 4;
    POWERLEVEL9K_IP_FOREGROUND = 0;
    POWERLEVEL9K_IP_CONTENT_EXPANSION = "'\${P9K_IP_RX_RATE:+⇣$P9K_IP_RX_RATE }\${P9K_IP_TX_RATE:+⇡$P9K_IP_TX_RATE }$P9K_IP_IP'";
    POWERLEVEL9K_IP_INTERFACE = "'[ew].*'";

    # Proxy
    POWERLEVEL9K_PROXY_FOREGROUND = 4;
    POWERLEVEL9K_PROXY_BACKGROUND = 0;

    # Battery (stages use \U escapes preserved via double-backslash in Nix "..." strings)
    POWERLEVEL9K_BATTERY_LOW_THRESHOLD = 20;
    POWERLEVEL9K_BATTERY_LOW_FOREGROUND = 1;
    POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND = 2;
    POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND = 2;
    POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND = 3;
    POWERLEVEL9K_BATTERY_STAGES = "'\\UF008E\\UF007A\\UF007B\\UF007C\\UF007D\\UF007E\\UF007F\\UF0080\\UF0081\\UF0082\\UF0079'";
    POWERLEVEL9K_BATTERY_VERBOSE = false;
    POWERLEVEL9K_BATTERY_BACKGROUND = 0;

    # WiFi
    POWERLEVEL9K_WIFI_FOREGROUND = 0;
    POWERLEVEL9K_WIFI_BACKGROUND = 4;

    # Time
    POWERLEVEL9K_TIME_FOREGROUND = 0;
    POWERLEVEL9K_TIME_BACKGROUND = 7;
    POWERLEVEL9K_TIME_FORMAT = "%D{%H:%M:%S}";
    POWERLEVEL9K_TIME_UPDATE_ON_COMMAND = false;

    # Transient prompt / instant prompt
    POWERLEVEL9K_TRANSIENT_PROMPT = "always";
    POWERLEVEL9K_INSTANT_PROMPT = "verbose";
    POWERLEVEL9K_DISABLE_HOT_RELOAD = true;
  };

  vcsExpansion = "'\${$((my_git_formatter()))+\${my_git_format}}'";
in
''
  'builtin' 'local' '-a' 'p10k_config_opts'
  [[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
  [[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
  [[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
  'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

  () {
    emulate -L zsh -o extended_glob
    unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'
    [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

    ${lib.concatStringsSep "\n    " (lib.mapAttrsToList toZsh settings)}

    function my_git_formatter() {
      emulate -L zsh
      if [[ -n $P9K_CONTENT ]]; then
        typeset -g my_git_format=$P9K_CONTENT
        return
      fi
      local meta='%7F' clean='%0F' modified='%0F' untracked='%0F' conflicted='%1F'
      local res
      if [[ -n $VCS_STATUS_LOCAL_BRANCH ]]; then
        local branch=''${(V)VCS_STATUS_LOCAL_BRANCH}
        (( $#branch > 32 )) && branch[13,-13]="…"
        res+=''${clean}''${(g::)POWERLEVEL9K_VCS_BRANCH_ICON}''${branch//\%/%%}
      fi
      if [[ -n $VCS_STATUS_TAG && -z $VCS_STATUS_LOCAL_BRANCH ]]; then
        local tag=''${(V)VCS_STATUS_TAG}
        (( $#tag > 32 )) && tag[13,-13]="…"
        res+=''${meta}#''${clean}''${tag//\%/%%}
      fi
      [[ -z $VCS_STATUS_LOCAL_BRANCH && -z $VCS_STATUS_TAG ]] && res+=''${meta}@''${clean}''${VCS_STATUS_COMMIT[1,8]}
      if [[ -n ''${VCS_STATUS_REMOTE_BRANCH:#$VCS_STATUS_LOCAL_BRANCH} ]]; then
        res+=''${meta}:''${clean}''${(V)VCS_STATUS_REMOTE_BRANCH//\%/%%}
      fi
      if [[ $VCS_STATUS_COMMIT_SUMMARY == (|*[^[:alnum:]])(wip|WIP)(|[^[:alnum:]]*) ]]; then
        res+=" ''${modified}wip"
      fi
      if (( VCS_STATUS_COMMITS_AHEAD || VCS_STATUS_COMMITS_BEHIND )); then
        (( VCS_STATUS_COMMITS_BEHIND )) && res+=" ''${clean}⇣''${VCS_STATUS_COMMITS_BEHIND}"
        (( VCS_STATUS_COMMITS_AHEAD && !VCS_STATUS_COMMITS_BEHIND )) && res+=" "
        (( VCS_STATUS_COMMITS_AHEAD )) && res+=''${clean}⇡''${VCS_STATUS_COMMITS_AHEAD}
      fi
      (( VCS_STATUS_PUSH_COMMITS_BEHIND )) && res+=" ''${clean}⇠''${VCS_STATUS_PUSH_COMMITS_BEHIND}"
      (( VCS_STATUS_PUSH_COMMITS_AHEAD && !VCS_STATUS_PUSH_COMMITS_BEHIND )) && res+=" "
      (( VCS_STATUS_PUSH_COMMITS_AHEAD )) && res+=''${clean}⇢''${VCS_STATUS_PUSH_COMMITS_AHEAD}
      (( VCS_STATUS_STASHES )) && res+=" ''${clean}*''${VCS_STATUS_STASHES}"
      [[ -n $VCS_STATUS_ACTION ]] && res+=" ''${conflicted}''${VCS_STATUS_ACTION}"
      (( VCS_STATUS_NUM_CONFLICTED )) && res+=" ''${conflicted}~''${VCS_STATUS_NUM_CONFLICTED}"
      (( VCS_STATUS_NUM_STAGED )) && res+=" ''${modified}+''${VCS_STATUS_NUM_STAGED}"
      (( VCS_STATUS_NUM_UNSTAGED )) && res+=" ''${modified}!''${VCS_STATUS_NUM_UNSTAGED}"
      (( VCS_STATUS_NUM_UNTRACKED )) && res+=" ''${untracked}''${(g::)POWERLEVEL9K_VCS_UNTRACKED_ICON:-'?'}''${VCS_STATUS_NUM_UNTRACKED}"
      (( VCS_STATUS_HAS_UNSTAGED == -1 )) && res+=" ''${modified}─"
      typeset -g my_git_format=$res
    }
    functions -M my_git_formatter 2>/dev/null
    typeset -g POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=true
    typeset -g POWERLEVEL9K_VCS_CONTENT_EXPANSION=${vcsExpansion}

    # If p10k is already loaded, reload configuration.
    (( ! $+functions[p10k] )) || p10k reload
  }

  typeset -g POWERLEVEL9K_CONFIG_FILE=''${''${(%):-%x}:a}

  (( ''${#p10k_config_opts} )) && setopt ''${p10k_config_opts[@]}
  'builtin' 'unset' 'p10k_config_opts'
''
