# ~/.config/matugen/templates/hyprlock-colors.conf
$primary_container = rgb({{colors.primary_container.default.hex_stripped}})
$on_primary_container = rgb({{colors.on_primary_container.default.hex_stripped}})
$outline = rgb({{colors.outline.default.hex_stripped}})
$backgroundAA = rgba({{colors.background.default.red}}, {{colors.background.default.green}}, {{colors.background.default.blue}}, 0.5)

# This variable allows hyprlock to always find your current wallpaper
$current_wallpaper = {{image}}