# Hardware configuration for stellyrland (x86_64-linux).
# Generated by nixos-generate-config; maintained manually from this point.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.kernelModules = ["kvm-amd"];

  fileSystems."/" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = ["subvol=@" "compress=zstd" "noatime" "discard=async" "commit=60" "space_cache=v2"];
    neededForBoot = true;
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = ["subvol=@nix" "compress=zstd" "noatime" "discard=async" "commit=60" "space_cache=v2"];
    neededForBoot = true;
  };

  fileSystems."/persist" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = ["subvol=@persist" "compress=zstd" "noatime" "discard=async" "commit=60" "space_cache=v2"];
    neededForBoot = true;
  };

  fileSystems."/home" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = ["subvol=@home" "compress=zstd" "noatime" "discard=async" "commit=60" "space_cache=v2"];
  };

  fileSystems."/home/.snapshots" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = ["subvol=@home_snapshots" "noatime" "compress=zstd" "discard=async" "commit=60" "space_cache=v2"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/STELLYRBOOT";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-partlabel/disk-main-swap";
      randomEncryption.enable = true;
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
