##--------------------------##
##------- Hyprland --------##
##--------------------------##

################
### MONITORS ###
################

# https://wiki.hypr.land/Configuring/Monitors/

# Monitor 1 (DP-2) - Primary Ultrawide
monitor = DP-2, 3440x1440@175, 1440x541, 1, bitdepth, 10, sdrbrightness, 1.2, sdrsaturation, 0.98

# Monitor 2 (DP-3) - Vertical
monitor = DP-3, 2560x1440@100, 0x0, 1, transform, 1, bitdepth, 10, sdrbrightness, 1.2, sdrsaturation, 0.98

# Fallback for slow initializing displays
monitor = , preferred, auto, 1

xwayland {
    force_zero_scaling = true
}

workspace = 1, monitor:desc:Samsung Electric Company Odyssey G85SB H1AK500000, persistent:true, default:true
workspace = 2, monitor:desc:Samsung Electric Company Odyssey G85SB H1AK500000, persistent:true
workspace = 3, monitor:desc:Samsung Electric Company Odyssey G85SB H1AK500000, persistent:true
workspace = 4, monitor:desc:Samsung Electric Company Odyssey G85SB H1AK500000, persistent:true
workspace = 5, monitor:desc:Samsung Electric Company Odyssey G85SB H1AK500000, persistent:true

#################
### AUTOSTART ###
#################

# exec-once = hyprpm reload -n

# Session environment
exec-once = hyprpolkitagent
exec-once = dbus-update-activation-environment --all
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = pipewire
exec-once = pipewire-pulse
exec-once = wireplumber
# Applets
exec-once = nm-applet
exec-once = mprisence
exec-once = hypridle

# Bar, wallpaper, dock
exec-once = quickshell

# Removable media
exec-once = udiskie -a -s --file-manager nautilus

############################
### ENVIRONMENT VARIABLES ##
############################

# https://wiki.hyprland.org/Configuring/Environment-variables/

# Cursor
env = XCURSOR_THEME, Bibata-Modern-Ice
env = HYPRCURSOR_SIZE, 16

# Qt
env = QT_QPA_PLATFORM, wayland;xcb
env = QT_QPA_PLATFORMTHEME, qt6ct
env = QT_STYLE_OVERRIDE, kvantum
env = QT_WAYLAND_DISABLE_WINDOWDECORATION, 1
env = QT_AUTO_SCREEN_SCALE_FACTOR, 1.25

# GTK
env = GDK_SCALE, 1.0
env = GTK_CSD, 0

# Wayland / XDG
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland

# App-specific
env = MOZ_ENABLE_WAYLAND, 1
env = ELECTRON_OZONE_PLATFORM_HINT, auto
env = OBS_USE_EGL, 1
env = PROTON_ENABLE_WAYLAND, 1
env = PROTON_ENABLE_HDR, 1

#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input

input {
    kb_layout = us
    kb_options = caps:escape
    numlock_by_default = true
    follow_mouse = 1
    sensitivity = 0
    accel_profile = flat
}

###############
### PLUGINS ###
###############

plugin {
    hyprexpo {
        columns = 3
        gap_size = 5
        bg_col = rgb(111111)
        workspace_method = center current
    }
}

###############
### SOURCES ###
###############

source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/rules.conf
