# ~/.config/matugen/templates/hyprlock-colors.conf
$primary_container = rgb(344479)
$on_primary_container = rgb(dce1ff)
$outline = rgb(8f909a)
$backgroundAA = rgba(18, 19, 24, 0.5)

# This variable allows hyprlock to always find your current wallpaper
$current_wallpaper = /home/stellanova/.cache/quickshell/wallpapers/1772191121.mp4.png