{
  wayland.windowManager.hyprland.settings = {
    windowrule = [
      "float on, match:class ^(Rofi)$"
      "float on, match:class ^(xdg-desktop-portal-gtk)$"
      "float on, match:class ^(zenity)$"
      "float on, match:class ^(org.pulseaudio.pavucontrol)$"
      "float on, match:title ^(File Operation Progress)$"
      "float on, match:title ^(Open File)$"
      "float on, match:title ^(Open Folder)$"
      "float on, match:title ^(Picture in picture)$"
      "float on, match:title ^(Picture-in-Picture)$"
      "center on, match:class ^(xdg-desktop-portal-gtk)$"
      "center on, match:class ^(zenity)$"
      "center on, match:class ^(org.pulseaudio.pavucontrol)$"
      "center on, match:title ^(Open File)$"
      "center on, match:title ^(Open Folder)$"
      "size 70% 70%, match:title ^(Select a Wallpaper)$"
      "size 32% 18%, match:title ^(Picture-in-Picture)$"
      "size 70% 50%, match:class ^(xdg-desktop-portal-gtk)$"
      "move 45% 30%, match:title ^(Confirm File Replacing)$"
      "move 18% 35%, match:title ^(Copying files)$"
      "move 18% 35%, match:title ^(Moving files)$"
      "float on, match:class ^(waypaper)$"
      "center on, match:class ^(waypaper)$"
      "size 70% 70%, match:class ^(waypaper)$"
      "pin on, match:class ^(waypaper)$"
      "pin on, match:title ^(Select a Wallpaper)$"
      "opacity 1.0 override, match:class ^(xdg-desktop-portal-gtk)$"
      "opacity 1.0 override, match:class ^(Xdg-desktop-portal-gtk)$"
      "opacity 0.85 override 0.75 override, match:class ^(org.gnome.Nautilus)$"
      "opacity 0.8 override 0.8 override 1.0 override, match:class ^(kitty)$"
      "opacity 0.3 override, match:class ^(nvim)$"
      "opacity 1.0 override 0.85 override 1.0 override, match:class ^(zen)$"
      "opacity 1.0 override 1.0 override, match:class ^(discord)$"
      "opacity 1.0 override 1.0 override, match:class ^(vesktop)$"
      "opacity 1.0 override, match:title ^(Picture in picture)$"
      "opacity 0.6 override 0.6 override 1.0 override, match:title (.*)(YouTube Music)(.*)"
      "no_shadow on, match:class ^(xdg-desktop-portal-gtk)$"
      "no_blur on, match:class ^(xdg-desktop-portal-gtk)$"
      "no_blur on, match:title ^(Picture in picture)$"
      "no_shadow on, match:title ^(Picture in picture)$"
      "animation popin override, match:class ^(rofi)$"
    ];

    layerrule = [
      "blur on, match:namespace noctalia-.*"
      "ignore_alpha 0.5, match:namespace noctalia-.*"
      "animation slide, match:namespace notifications"
      "no_anim on, match:namespace wallpaper-transition"
    ];
  };
}
