[config]
# The directory to put the generated wallpaper
wallpaper_dir = "~/.config/matugen/"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/colors.conf"
[templates.hyprlock]
input_path = "~/.config/matugen/templates/hyprlock-colors.conf"
output_path = "~/.config/hypr/hyprlock-colors.conf"
[templates.cava]
input_path = "~/.config/matugen/templates/cava-colors.ini"
output_path = "~/.config/cava/themes/colors"
[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/current-theme.conf"
[templates.zed]
input_path = "~/.config/matugen/templates/matugen.json"
output_path = "~/.config/zed/themes/matugen.json"
[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk4-colors.css"
output_path = "~/.config/gtk-4.0/colors.css"
[templates.nvim]
input_path = "~/.config/matugen/templates/nvim-colors.lua"
output_path = "~/.config/nvim/lua/matugen_colors.lua"
[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell-colors.json"
output_path = "~/.config/quickshell/colors.json"
