keys:
  - &user_stellanova age1muxquz7vyrsva0me3q68mf9xak578hzejqm39vr3llfsftc0dcpqaxlaf7
  - &host_stellyrland age1nj6sxp93n7sulqvndsquh4rs73lx0uy5pdec5y4r4642dpwh2v2qwzukh6
  # Installed stellyrlab host key.
  - &host_stellyrlab age1w3gaesy5c9kkw95843qf4d84zp8ghes0zvhselnnakxzccd4pcksvn3fet
  - &host_plasmapulsefinale age1ltjn45ay4nwrtx8k9f86ylk5zth98xz9t2gxwe6c2ws3wm44sses9hgc9t
  - &host_stellyrtop age1uvrlydzt2htytadw230ugj0sndfjhtl945n5hn0gtgjhpp5g4u6qtcma05
  - &host_ItsRedFlame age1rzxcemflrpsfyxtnenc3ma678s4j72kfzfxu8vnlj6mz6mxqlassn4y9ev
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - pgp: []
        age:
          - *user_stellanova
          - *host_stellyrland
          - *host_stellyrlab
          - *host_stellyrtop
  - path_regex: harmonia\.yaml$
    key_groups:
      - pgp: []
        age:
          - *user_stellanova
          - *host_stellyrland
  - path_regex: plasmapulsefinale\.yaml$
    key_groups:
      - pgp: []
        age:
          - *user_stellanova
          - *host_plasmapulsefinale
  - path_regex: ItsRedFlame\.yaml$
    key_groups:
      - pgp: []
        age:
          - *user_stellanova
          - *host_ItsRedFlame
