keys:
  - &user_stellanova age1uvrlydzt2htytadw230ugj0sndfjhtl945n5hn0gtgjhpp5g4u6qtcma05
  - &host_stellyrland age1nj6sxp93n7sulqvndsquh4rs73lx0uy5pdec5y4r4642dpwh2v2qwzukh6
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - pgp: []
        age:
          - *user_stellanova
          - *host_stellyrland
