keys:
  - &user_stellanova age1zafs5u68l02nt2gs76necgez5ccvfgpmvwhvhu5vyd70qw94sd5sx95q6p
  - &host_stellyrland age1nj6sxp93n7sulqvndsquh4rs73lx0uy5pdec5y4r4642dpwh2v2qwzukh6
  - &host_onitop age15teg2f9a2tae7u62yzggherl4wrwfks9zcwvvrq32ck5hzyeldcqa8jgmm
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - pgp: []
        age:
          - *user_stellanova
          - *host_stellyrland
  - path_regex: onitop\.yaml$
    key_groups:
      - pgp: []
        age:
          - *user_stellanova
          - *host_onitop
